### Application configuration ###
# The name of the application. Used in cloud resource names (Cloud Run services, Cloud Load Balancer, etc.).
app_name: answer-app

# The location for discoveryengine API (Agent Builder) resources. One of global, us, or eu.
location: global

# The Agent Builder Data Store and Search Engine IDs to provision with Terraform.
data_store_id: answer-app-data-store
search_engine_id: answer-app-search-engine

# The company name used in the Agent Builder Search Engine.
customer_name: Cymbal

# A custom preamble to use in the google.cloud.discoveryengine.v1.AnswerQueryRequest.AnswerGenerationSpec.PromptSpec.
preamble: |
  You are a helpful answering assistant. Your job is to condense and summarize information and answer questions succinctly to save time for the user.

  Use the information in the documents to provide accurate answers to the questions you receive. Refer to all previous conversation turns in this session for added context.

  Provide concise answers with enough detail to sufficiently support them using meaningful citations from the documents.

  Format your responses using markdown. Use clear separation of topics and themes with line and paragraph breaks.

  Use bulleted lists only when appropriate to make the information easy to read and understand.


### Infrastructure components configuration ###
# Set create_loadbalancer to false to deploy the app to Cloud Run without a load balancer.
create_loadbalancer: true

# Set loadbalancer_domain to a domain you control. Requires editing your domain's DNS zone A record to point to the load balancer IP address.
# Set to 'null' to use an auto-generated domain with https://nip.io. Does not require DNS configuration.
loadbalancer_domain: null

# Big Query dataset and table IDs to store conversation details.
dataset_id: answer_app
table_id: conversations
