[auth]
redirect_uri = "replace_with_the_oauth_client_configured_redirect_uri"
cookie_secret = "replace_with_a_cryptographically_secure_random_password"

[auth.google]
client_id = "replace_with_real_client_id"
client_secret = "replace_with_real_client_secret"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
client_kwargs = { "access_type" = "online", "prompt" = "select_account" }
