name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: "2.0.0"
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: poetry install --with dev

    - name: Run tests
      run: poetry run pytest tests/test_main.py tests/test_utils.py tests/test_discoveryengine_utils.py tests/test_model.py tests/test_write_secrets_toml.py

    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@v9.15.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        root_options: "-vv"